

# default destination
# when no SNI name found
# or parse TLS HELLO message failed
default: 127.0.0.1:8443

# the port listen on
# can specify multiple ports
listen:
  - 80
  - 443
  - 9999

# forward rules
# exact match or wildcard match
forward_rules:
  # forward by domain and port to 127.0.0.1:8080
  www.example.com:80: 127.0.0.1:8080

  # www.example.com forward to 127.0.0.1:8443
  www.example.com: 127.0.0.1:8443

  # b.example.com forward to 127.0.0.1:8541
  b.example.com: 127.0.0.1:8541

  # forward by wildcard domain
  # eg: forward a.example.com:9999 to a.example.com:443
  "*:9999": "*:443"
